# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33c0691d9cd5a96fbd730925b9def0ecf6fd5a18f0b04bf8fe940f85ca0db7aee68859b657288adfb32434bb89a50813bdc42847c9fc39d57d77388dc7d15bc7

test:
  secret_key_base: d4cea5cc8074759dd098a1e966fa69cb1e274f8f6dbfee7a2ae87061e3c4f2e2933472bdec17f88bcaf323b29404fdfc516f8f391fa30f9c90b92ffd441f8379

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
